name: On Test End
run-name: ${{ github.workflow }} (${{ github.head_ref || github.ref_name }})
on:
  workflow_run:
    workflows: [Workflow test]
    types: [completed]
    branches:
      - oris/1.3.0

jobs:
  test:
    name: On Test End
    runs-on: ubuntu-latest
    steps:
      - name: On Test End
        run: echo "Test End"
