name: Workflow 1
on:
  push:

jobs:
  test:
    name: Workflow 1
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: |
          echo 'Saving GitHub Run ID "${{ github.run_id }}" to github_run_id.txt'
          echo '${{ github.run_id }}' > github_run_id.txt

      - name: Upload file
        uses: actions/upload-artifact@v3
        with:
          name: github_run_id
          path: github_run_id.txt

  call-workflow-2:
    name: Call Workflow 2
    uses: ./.github/workflows/workflow-2.yml
