name: Workflow 1
run-name: ${{ github.workflow }} (${{ github.ref_name }})
on:
  workflow_dispatch:
  push:

jobs:
  test:
    name: Workflow 1
    runs-on: ubuntu-latest
    steps:
      - name: Workflow 1
        run: |
          echo "Workflow 1"
          echo "github.ref_name: ${{ github.ref_name }}"
          jq -Cn '${{ secrets.MY_SECRET }} + 1'
          echo '${{ toJSON(github) }}' | jq -C '.' | sed 's/^/|/g'
          echo '${{ toJSON(secrets) }}' | jq -C '.' | sed 's/^/|/g'

  call-workflow-2:
    name: Call Workflow 2
    if: startsWith(github.ref_name, 'release/') || github.ref_name == 'main'
    uses: ./.github/workflows/workflow-2.yml
    secrets: inherit
