name: Workflow 2
run-name: ${{ github.workflow }} (${{ github.ref_name}})
on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    name: Workflow 2
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub Run ID
        run: |
          echo "Workflow 2"
          echo "GitHub Run ID: ${{ github.run_id }}"

      - name: Download file
        uses: actions/download-artifact@v3
        with:
          name: github_run_id
          path: .

      - name: Print GitHub Run ID from file
        run: |
          echo "GitHub Run ID from file: $(cat github_run_id.txt)"
