name: Workflow 2
run-name: ${{ github.workflow }} (${{ github.ref_name}})
on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    name: Workflow 2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print GitHub Run ID
        run: |
          echo "ACTIONS_RUNTIME_URL: $ACTIONS_RUNTIME_URL"
          echo "Workflow 2"
          echo "GitHub Run ID: ${{ github.run_id }}"

      - name: Use composite action to download file
        uses: ./.github/actions/download-artifact
        with:
          workflow-name: Workflow 1
          name: github_run_id
          path: .

      - name: Print GitHub Run ID from file
        run: |
          echo "GitHub Run ID from file: $(cat github_run_id.txt)"
